### ISSUE TITLE
Coverage always fails with Error: Expected key

### ISSUE THREAD

**Issue by ggonzalez94** [software-mansion/cairo-coverage#53]
**Versions**
- cairo-coverage: 0.1.0
- snforge: 0.30.0
- scarb: 0.28

**Describe the bug**
I created a brand new `snforge` project and tried to get coverage both by running `snforge test --coverage` and by using `cairo-coverage` directly on the json files and it always fails with message:
```sh
Error: Expected key: github.com/software-mansion/cairo-coverage but was missing
```

**To Reproduce**
- Steps to reproduce the behavior:
1. Create a new starknet foundry project by doing `snforge init my_project`
2. Run `snforge test --coverage`

**Expected behavior**
Coverage report should be generated successfully.

**Comment by maciektr** [comment]
As stated in [the docs](https://foundry-rs.github.io/starknet-foundry/testing/coverage.html), you need to add following section to your `Scarb.toml` manifest first.

```
[cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"
```

You can use

**Comment by ksew1** [comment]
Hi @ggonzalez94,

Did that help you, or are you still encountering this issue? Also, please remember that currently, coverage doesn't work on contracts.

**Comment by ggonzalez94** [comment]
Hey @maciektr @ksew1 thanks this solved it. I'm closing the issue.

> coverage doesn't work on contracts.
I guess this applies to components as well?
