### ISSUE TITLE
Implement an independent library for mapping code

### ISSUE THREAD

**Issue by Arcticae** [software-mansion/cairo-coverage#62]
This is to be used in `snforge` (for printing latest failed line), `cairo-coverage`, and `cairo-profiler` 

This should include: 
- `CallTrace` structure definition (versioned, like `cairo-lang`'s `VersionedProgram`, so that we can recover from failures on unmatched/unsupported versions, with aborting the print)
- Definition of mappings structures for `coverage` and `profiler`
- This function:
```
fn map_vm_trace<T>(
  vm_trace: Vec<TraceEntry>,
  casm_debug_info: CasmDebugInfo,
  sierra_mapping: HashMap<StatementIdx, T>,
  run_with_header: bool,
) -> MappingResult<T>
```
and this structure:
```
MappingResult<T> {
   Concrete(T)
   Header,
   PcOutOfFunctionArea,
}
```

**Comment by Arcticae** [comment]
cc @piotmag769 to provide the rationale

**Comment by piotmag769** [comment]
Is this really done?
